<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log in to Facebook</name>
   <tag></tag>
   <elementGuidId>0d7385a4-ec34-4a9d-9f7f-9efd642aab05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header_block']/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._9axz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Log in to Facebook&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>879787d3-d06f-463a-89c5-0adb44d47e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9axz</value>
      <webElementGuid>62073940-0918-4efc-80cd-dc582d1164d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in to Facebook</value>
      <webElementGuid>34425614-d8a9-469b-bc9f-fa9a2dde0a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_block&quot;)/span[@class=&quot;_97w1 _50f6&quot;]/div[@class=&quot;_9axz&quot;]</value>
      <webElementGuid>8731b1a8-d465-4868-9606-32ebdfb59b0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header_block']/span/div</value>
      <webElementGuid>6c5383c7-b4a2-4c9f-9a80-a292f407b56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::div[8]</value>
      <webElementGuid>66ee4f70-d1d6-48d9-826f-5b57d0d632c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten account?'])[1]/preceding::div[9]</value>
      <webElementGuid>adae610c-7ac2-493f-be86-53f0523505f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>685f1498-d5ee-48c8-a341-a866e47a0aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Log in to Facebook' or . = 'Log in to Facebook')]</value>
      <webElementGuid>53426fca-0ea8-4d57-b94d-74425dc80857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
