<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Log in to Facebook__9ay6 img</name>
   <tag></tag>
   <elementGuidId>310092ac-736a-4a31-8a2a-bfca7cfcbf81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='email_container']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img._9ay6.img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#email_container img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>07de2f01-46c3-4c96-92c3-dd2ac58c479a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9ay6 img</value>
      <webElementGuid>9d37bcb9-0468-4b54-b2fa-40c2e87a3bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.xx.fbcdn.net/rsrc.php/v3/y2/r/O287_AcFyg4.png</value>
      <webElementGuid>d373fd92-f115-4f88-bb28-971d42ad2c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>19c48e92-298e-4929-a56e-e70b2d718492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f9e26583-3659-47ab-9512-6134f2d8fef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_container&quot;)/div[@class=&quot;_9ay5&quot;]/img[@class=&quot;_9ay6 img&quot;]</value>
      <webElementGuid>7d715f70-5646-43ce-a90f-c065134e075f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='email_container']/div/img</value>
      <webElementGuid>22bfec9c-c01f-403c-a752-02abcabf9aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://static.xx.fbcdn.net/rsrc.php/v3/y2/r/O287_AcFyg4.png')]</value>
      <webElementGuid>99b186d0-f948-4ce1-9f41-81e9f596d66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/img</value>
      <webElementGuid>bab9df0b-6069-4c6f-b211-dac17378d79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.xx.fbcdn.net/rsrc.php/v3/y2/r/O287_AcFyg4.png']</value>
      <webElementGuid>3ec6dd6e-4bcb-454a-bc2d-391a0bbdb23b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
