<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create new account</name>
   <tag></tag>
   <elementGuidId>38ba22d5-a05c-4b2f-a96b-31a02b8338d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='u_0_0_7a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_0_0_7a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;open-registration-form-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>40d1b362-f7d2-433b-a93d-286c07e73efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c40fc620-72b3-49bc-b910-98349c93876c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _6lti _4jy6 _4jy2 selected _51sy</value>
      <webElementGuid>0bd19d33-8422-40f3-9314-431704f9dfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9592cc92-b5e0-4361-aa8f-61f2c880af03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ajaxify</name>
      <type>Main</type>
      <value>/reg/spotlight/</value>
      <webElementGuid>bd1d32a7-9bff-45ca-a28d-955fec55d17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_0_7a</value>
      <webElementGuid>15f03a46-4d0e-4e89-9946-cc1d53503df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>open-registration-form-button</value>
      <webElementGuid>1e483a4c-c768-46b5-a1b5-a46ca112c68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>7e7bc5c4-7e81-4ba7-9352-99a071f71789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create new account</value>
      <webElementGuid>8d454969-fc3b-49b2-a0c3-5ee80998fcd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_0_7a&quot;)</value>
      <webElementGuid>15bd066f-f36a-4d78-b72a-d04dc31fa1ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='u_0_0_7a']</value>
      <webElementGuid>dfd2afe5-304d-4b96-a95d-453d3a922b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_Pn']/div[5]/a</value>
      <webElementGuid>6724d65e-2110-4eaf-933c-9fc7e56b92d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create new account')]</value>
      <webElementGuid>29500f7b-48f2-4178-84e3-983b217ec115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten password?'])[1]/following::a[1]</value>
      <webElementGuid>edc56d1c-93f7-48a7-ac59-13f74199031d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::a[2]</value>
      <webElementGuid>8eae455a-cb8d-4cc2-acce-f5f23f9a97ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a Page'])[1]/preceding::a[1]</value>
      <webElementGuid>f69d98a7-8776-429b-878c-761898f0c6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create new account']/parent::*</value>
      <webElementGuid>1298e09c-40a7-4b2d-b1b9-70160a75ffe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>6a36e03c-2fad-4fca-b72e-9b21d94aa20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>03460d57-fdd7-440f-9d07-df2a84b37c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'u_0_0_7a' and (text() = 'Create new account' or . = 'Create new account')]</value>
      <webElementGuid>dc710d6a-c898-4432-baa7-2dd365e8eb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='u_0_0_AJ']</value>
      <webElementGuid>ecb06f8e-f810-4ebc-b3a1-762996b591f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_Ss']/div[5]/a</value>
      <webElementGuid>a192f8af-1645-403e-917a-5fa939751bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'u_0_0_AJ' and (text() = 'Create new account' or . = 'Create new account')]</value>
      <webElementGuid>cc3c54d0-cf59-469e-a588-2e9bdcffbd8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
